
spring:
  ## 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.115.89:3306/jicai?useSSL=false&characterEncoding=utf-8
    username: root
    password: Scnu1123$
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache-shiro.xml
  servlet:
    multipart:
      max-file-size: 8MB
  #redis配置
  redis:
    database: 1
    host: 111.230.15.89
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-idle: 100
        max-wait: 10
    password: 123456

#mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml

#shiro配置
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index

  cache:
    # cookie生效时间，单位秒
    maxAge: 3600

#tomcat配置
server:
  port: 8081
  error:
    path: /error
  tomcat:
    #初始化线程数
    min-spare-threads: 10
    #最大线程数
    max-threads: 100
  #超时时间设置
  connection-timeout: 5000


#文件配置
file:
  default:
    dir: /usr/local/mdsoftware/wwwroot/files
    ip: www.hxxxpt.com
  qrCore:
    dir: /usr/local/mdsoftware/wwwroot/files/qrcore/


#日志配置
logging:
  level:
    com.nanshen.module.system.dao: debug


#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

