
spring:
  ## 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://211.149.161.57:3306/jicai?useSSL=false&characterEncoding=utf-8
    username: root
    password: thinkit2017
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache-shiro.xml
  servlet:
    multipart:
      max-file-size: 8MB

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml

shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index

  cache:
    # cookie生效时间，单位秒
    maxAge: 3600
server:
  port: 8081
  error:
    path: /error

file:
  default:
    dir: /usr/local/mdsoftware/wwwroot/JiCaiZhongBao/files
    ip: www.hxxxpt.com

logging:
  level:
    com.nanshen.module.system.dao: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

